<a href="https://colab.research.google.com/github/momoT2/2-project/blob/feature_ja/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%95%EA%B7%9C%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [38]:
# 데이터 불러오기
import pandas as pd
data_url = '/content/drive/My Drive/MedicalDA03/data/2PD_v2_0825.csv'
raw_df = pd.read_csv(data_url)

In [39]:
# 복사본 만들기
df = raw_df

In [40]:
df

,id,burnout60,area,gender,age,wduration_y,earning1,earning2_r,wtime_r,woutside4_a,...,district,household,target,mode,hh_num,eli_num,hm_01_gender,hm_01_year,hm_01_estat,hm_01_rel_t
0,1000042_1,lv1,1,1,49,10,500,6,40,1,...,10001,1000042,1,1,3,2,1,1974,2,0
1,1000051_1,lv2,1,1,31,2,300,4,48,1,...,10001,1000051,1,1,1,1,1,1992,2,0
2,1000056_1,lv1,1,1,32,2,300,4,50,1,...,10001,1000056,1,1,1,1,1,1991,2,0
3,1000069_1,lv1,1,1,38,2,390,4,40,1,...,10002,1000069,1,1,2,2,1,1985,2,0
4,1000069_2,lv1,1,2,37,5,330,4,40,1,...,10002,1000069,2,1,2,2,1,1985,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10152,2009807_1,lv1,13,1,31,1,250,3,48,1,...,15003,2009807,1,1,1,1,1,1992,2,0
10153,2010133_1,lv2,7,2,46,3,230,3,40,1,...,15007,2010133,1,1,1,1,2,1977,2,0
10154,2010134_2,lv1,7,2,34,5,320,4,40,1,...,15007,2010134,2,1,3,3,2,1961,3,0
10155,2010137_1,lv1,7,1,57,5,450,5,40,1,...,15007,2010137,1,1,2,2,1,1966,2,0
10156,2010137_2,lv1,7,2,29,3,350,4,40,1,...,15007,2010137,2,1,2,2,1,1966,2,0

In [41]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# 정규화할 열 리스트
ordinal_cols = ["emp_manaqual_a",
	"emp_manaqual_b",
	"emp_manaqual_c",
	"emp_manaqual_d",
	"emp_manaqual_e",
	"emp_comp_ass_a",
	"emp_comp_ass_b",
	"emp_comp_ass_c",
	"emp_comp_ass_d",
	"emp_comp_ass_e",
	"emp_comp_ass_f",
	"emp_winflu_a",
	"emp_winflu_b",
	"emp_winflu_c",
	"imte1",
	"imte2",
	"imte3",
	"imte4",
	"imte5",
	"safeinform",
	"wsituation1",
	"wsituation2",
	"wsituation3",
	"wsituation4",
	"wsituation5",
	"wsituation11",
	"wsituation6",
	"wsituation7",
	"wsituation8",
	"wsituation9",
	"wsituation10",
	"wsituation12",
	"wsituation13",
	"wsituation14",
	"wstat1",
	"wstat2",
	"wstat3",
	"wstat4",
	"wstat5",
	"wstat6",
	"wstat7",
	"wtime_arr_a",
	"wtime_ftwork",
	"wtime_ftcomtool",
	"wtime_private",
	"hazard_phy_b",
	"hazard_erg_a",
	"hazard_erg_b",
	"hazard_erg_c",
	"hazard_erg_d",
	"hazard_erg_e",
	"winten2_a",
	"winten2_b",
	"winterrupt1",
	"weng1",
	"weng2",
	"weng3",
	"weng4",
	"weng5",
	"satisfaction",
	"wplace4",
	"wplace3",
	"wplace2",
	"wplace1",
	"wpalce_ch",
	"wbalance",
	"wwa1",
	"wwa2",
	"wwa3",
	"wwa4",
	"wwa5",
	"heal_cond",
	"heal_lim1",
	"sleep1",
	"sleep2",
	"sleep3",
	"who1",
	"who2",
	"who3",
	"who4",
	"who5",
	"woutside3",
	"woutside4",
	"woutside5",
	"income_bal"
	]

# Min-Max 정규화 객체 생성
scaler = MinMaxScaler()

# 서열척도 열만 정규화
df[ordinal_cols] = scaler.fit_transform(df[ordinal_cols])

# 결과 확인
print(df[ordinal_cols].head())

# 저장
#df.to_excel("normalized_data.xlsx", index=False)

   emp_manaqual_a  emp_manaqual_b  emp_manaqual_c  emp_manaqual_d  \
0            0.50            0.50            0.25            0.25
1            0.50            0.50            0.50            0.25
2            0.25            0.25            0.50            0.25
3            0.00            0.50            0.00            0.25
4            0.25            0.00            0.00            0.25

   emp_manaqual_e  emp_comp_ass_a  emp_comp_ass_b  emp_comp_ass_c  \
0            0.25            0.50            0.25            0.25
1            0.25            0.25            0.25            0.50
2            0.50            0.25            0.25            0.50
3            0.25            0.25            0.00            0.50
4            0.00            0.25            0.50            0.00

   emp_comp_ass_d  emp_comp_ass_e  ...  sleep3  who1  who2  who3  who4  who5  \
0            0.25            0.25  ...    0.75   0.4   0.4   0.4   0.2   0.2
1            0.50            0.50  ...    0.75   0.4   0.4   0.4   0.2   0.2
2            0.50            0.50  ...    0.75   0.2   0.2   0.6   0.4   0.4
3            0.00            0.25  ...    0.75   0.2   0.0   0.4   0.0   0.2
4            0.50            0.00  ...    1.00   0.2   0.0   0.4   0.0   0.2

   woutside3  woutside4  woutside5  income_bal
0       0.75       0.50       1.00         0.6
1       0.25       0.75       0.75         0.4
2       0.25       0.75       1.00         0.4
3       0.00       1.00       1.00         0.0
4       0.00       1.00       1.00         0.0

[5 rows x 85 columns]

In [43]:
# 데이터 저장
df.to_csv("2PD_v3_0825.csv", index=False, encoding="utf-8-sig")